RawData/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'RawData'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^thankyou$', views.thankyou, name='thankyou'),
    url(r'^school_request', views.school_request, name='school_request'),
    url(r'^position_request', views.position_request, name='position_request'),
    url(r'^addstaff_request', views.addstaff_request, name='addstaff_request'),
]

hris/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('RawData.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

RawData/models.py
from django.db import models


class StaffData(models.Model):
    objects = models.Manager()
    surName = models.CharField(max_length=500, default='', null=False, blank=False)
    firstName = models.CharField(max_length=500, default='', null=False, blank=False)
    middleName = models.CharField(max_length=500, default='', null=False, blank=False)
    extensionName = models.CharField(max_length=500, default='', null=False, blank=False)
    dateBirth = models.DateField(null=True)
    placeBirth = models.CharField(max_length=500, default='', null=False, blank=False)
    sex = models.CharField(max_length=500, default='', null=False, blank=False)
    civilStatus = models.CharField(max_length=500, default='', null=False, blank=False)
    gsisId = models.CharField(max_length=500, default='', null=False, blank=False)
    pagibigId = models.CharField(max_length=500, default='', null=False, blank=False)
    philhealthId = models.CharField(max_length=500, default='', null=False, blank=False)
    tinId = models.CharField(max_length=500, default='', null=False, blank=False)
    mobileNum = models.CharField(max_length=500, default='', null=False, blank=False)
    depedEmail = models.CharField(max_length=500, default='', null=False, blank=False)
    positionType = models.ForeignKey('RawData.PositionType', default='', null=False, blank=False,
                                     on_delete=models.CASCADE)
    positionName = models.ForeignKey('RawData.Position', default='', null=False, blank=False,
                                     on_delete=models.CASCADE)
    districtName = models.ForeignKey('RawData.District', default='', null=False, blank=False,
                                     on_delete=models.CASCADE)
    schoolName = models.ForeignKey('RawData.School', default='', null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.surName


class District(models.Model):
    objects = models.Manager()
    districtName = models.CharField(max_length=255, default='', null=False, blank=False)

    def __str__(self):
        return self.districtName


class School(models.Model):
    objects = models.Manager()
    districtName = models.ForeignKey('RawData.District', default='', null=False, blank=False,
                                     on_delete=models.CASCADE)
    schoolName = models.CharField(max_length=255, default='', null=False, blank=False)

    def __str__(self):
        return self.schoolName


class PositionType(models.Model):
    objects = models.Manager()
    positionType = models.CharField(max_length=255, default='', null=False, blank=False)

    def __str__(self):
        return self.positionType


class Position(models.Model):
    objects = models.Manager()
    positionType = models.ForeignKey('RawData.PositionType', default='', null=False, blank=False,
                                     on_delete=models.CASCADE)
    positionName = models.CharField(max_length=255, default='', null=False, blank=False)

    def __str__(self):
        return self.positionName

RawData/forms.py
from django import forms
from RawData.models import  District, School, Position, PositionType


class StaffForm(forms.Form):
    surName = forms.CharField(max_length=500, required=True)
    firstName = forms.CharField(max_length=500, required=True)
    middleName = forms.CharField(max_length=500, required=True)
    extensionName = forms.CharField(max_length=500, required=True)
    dateBirth = forms.DateField(required=True)
    placeBirth = forms.CharField(max_length=500, required=True)
    sex = forms.CharField(max_length=500, required=True)
    civilStatus = forms.CharField(max_length=500, required=True)
    gsisId = forms.CharField(max_length=500, required=True)
    pagibigId = forms.CharField(max_length=500, required=True)
    philhealthId = forms.CharField(max_length=500, required=True)
    tinId = forms.CharField(max_length=500, required=True)
    mobileNum = forms.CharField(max_length=500, required=True)
    depedEmail = forms.CharField(max_length=500, required=True)
    positionType = forms.ModelChoiceField(
        required=True,
        to_field_name="pk",
        queryset=PositionType.objects.all()
    )
    positionName = forms.ModelChoiceField(
        required=True,
        to_field_name="pk",
        queryset=Position.objects.all()
    )
    districtName = forms.ModelChoiceField(
        required=True,
        to_field_name="pk",
        queryset=District.objects.all()
    )
    schoolName = forms.ModelChoiceField(
        required=True,
        to_field_name="pk",
        queryset=School.objects.all()
    )

RawData/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .import views
from .models import StaffData, District, School, Position, PositionType
from .forms import StaffForm
import pdb


def index(request):
    district = District.objects.all()
    school = School.objects.all()
    positionType = PositionType.objects.all()
    context = {
        'district': district,
        'school': school,
        'positionType': positionType

    }
    return render(request, 'index.html', context)


def school_request(request):

    if request.method == 'POST':
        district_id = request.POST.get('id', None)
        school = School.objects.filter(districtName=district_id).values("id", "schoolName")
        return JsonResponse({"data": list(school)})
    else:
        return HttpResponse()


def position_request(request):
    if request.method == 'POST':
        positiontype_id = request.POST.get('id', None)
        position = Position.objects.filter(positionType=positiontype_id).values("id", "positionName")
        return JsonResponse({"data": list(position)})
    else:
        return HttpResponse()


def addstaff_request(request):
    if request.method == 'POST':
        form = StaffForm(data=request.POST)

        if form.is_valid():
            datas = form.cleaned_data
            StaffData.objects.create(
                surName =datas['surName'],
                firstName =datas['firstName'],
                middleName =datas['middleName'],
                extensionName =datas['extensionName'],
                dateBirth =datas['dateBirth'],
                placeBirth =datas['placeBirth'],
                sex =datas['sex'],
                civilStatus =datas['civilStatus'],
                gsisId =datas['gsisId'],
                pagibigId =datas['pagibigId'],
                philhealthId =datas['philhealthId'],
                tinId =datas['tinId'],
                mobileNum =datas['mobileNum'],
                depedEmail =datas['depedEmail'],
                positionType =datas['positionType'],
                positionName =datas['positionName'],
                districtName =datas['districtName'],
                schoolName =datas['schoolName'],
            )
            return JsonResponse({
                "success": True,
            })
        return JsonResponse({
            "success": False,
            "message": form.errors
        })


def thankyou(request):
    return render(request, 'thankyou.html')

RawData/templates/thankyou.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Thank You - HRIS Davao Del Norte</title>
        <link href="/static/css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
        <link rel="apple-touch-icon" sizes="180x180" href="\static\assets\img\apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="\static\assets\img\favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="\static\assets\img\favicon-16x16.png">
        <link rel="manifest" href="\static\assets\img\site.webmanifest">
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <main>
                    <div class="container">
                        <div class="row justify-content-center" style="margin-top:200px">
                            <div class="col-lg-4">
                                 <img src="\static\assets\img\thankyou.png" class="img-fluid" alt="Responsive image" />
                            </div>
                        </div>
                        <div class="row justify-content-center">
                             <a href="{% url 'RawData:index' %}"><button type="button" class="btn btn-primary" style="float:right"> Register Another Information</button></a>
                        </div>
                    </div>
            </main>
        </div>
    </body>
    <script src="https://blackrockdigital.github.io/startbootstrap-sb-admin/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-sb-admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</html>